benpelumiscrumy/urls.py
# from django.urls import path
# from benpelumiscrumy import views


# urlpatterns = [
#     path('', views.homePage, name='home'),
# ]

from django.urls import path, include
# from .views import homePage
from benpelumiscrumy import views

app_name = 'benpelumiscrumy'
urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal, name='moveGoal'),
    path('addgoal/', views.add_goal, name='addGoal'),
    path('home/', views.home, name='home'),
    path('homealone/<int:goal_id>', views.homealone),
    # path('homealone/<int:goal_id>', views.homealone),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts')
]

myscrumy/django-benpelumiscrumy/benpelumiscrumy/urls.py
# from django.urls import path
# from benpelumiscrumy import views


# urlpatterns = [
#     path('', views.homePage, name='home'),
# ]

from django.urls import path
from .views import homePage


urlpatterns = [
    path('', homePage, name='home'),
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
# from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path ('benpelumiscrumy/', include('benpelumiscrumy.urls', namespace = 'benpelumiscrumy')),
    path('websocket/', include('websocket.urls')),
    # path ('movegoals/', include('benpelumiscrumy.urls'))
]

# handler404 = 'benpelumiscrumy.views.error_404_view'
# benpelumiscrumy/
# git remote add origin https://github.com/THErealARETE/myscrumy.git
# git push -u origin master

benpelumiscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from random import randint

# Create your models here.

class GoalStatus(models.Model):
    status_name = models.CharField(max_length = 30)

    def __str__(self):
        return self.status_name    
# default = 1,unique=True,
class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length = 30)
    goal_id = models.IntegerField(default = 4,  unique = True )
    created_by = models.CharField(max_length = 30)
    moved_by = models.CharField(max_length = 30)
    owner = models.CharField(max_length = 30)
    # goal_description = models.TextField()
    goal_status = models.ForeignKey(
        GoalStatus,
        on_delete = models.PROTECT,
        related_name='scrumy_goal',
        # null = True
    ) 
    user = models.ForeignKey(
        User,
        on_delete = models.PROTECT,
        related_name = 'goal_owner'
    )

    def __str__(self):
        return self.goal_name
       

class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length = 30)
    created_by = models.CharField(max_length = 30)
    moved_from = models.CharField(max_length = 50)
    moved_to = models.CharField(max_length = 50)
    time_of_action = models.DateField()
    goal = models.ForeignKey(
        ScrumyGoals,
        on_delete = models.PROTECT
    )
    def __str__(self):
        return self.created_by 

myscrumy/django-benpelumiscrumy/benpelumiscrumy/models.py
from django.db import models

# Create your models here.

benpelumiscrumy/forms.py
#lab 19a
#Create two form classes SignupForm and CreateGoalForm. 
# The signup form will contain fields from the User model such as first_name,last_name,email,username,password
#  and the CreateGoalForm will contain the goal_name field and user field from the ScrumyGoals model. 
# The user field will enable a user of you application select the particular user the goal is being created for.

from django import forms

from .models import ScrumyGoals, User

class CreateGoalForm(forms.ModelForm):

    class Meta:
        model = ScrumyGoals
        fields = ('goal_name', 'user','goal_status')

class SignUpForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name','last_name','email', 'username', 'password')

class EditGoalForm(forms.ModelForm):

    class Meta:
        model = ScrumyGoals
        fields = ('goal_name', 'goal_status' )


        # 'goal_decription'

benpelumiscrumy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse 
from  .models import *
from .forms import *
# import datetime
from random import randint
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
# from django.urls import reverse


#lab 19b
# Reconstruct your index view such that it is used to create a new user account on your application.
#  When a GET request is sent to the view the view should render an empty SignupForm on an index.html template
#  and if its a POST request, all the form data should be processed and saved on the database.
def index(request) :
      if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                 temp =  form.save(commit = False)   
                 temp.set_password(request.POST.get('password'))
                 temp.save()                          
                 my_group = Group.objects.get(name='Developer') 
                 users = User.objects.get(username = temp.username) 
                 my_group.user_set.add(users)
                 return redirect('/benpelumiscrumy/accounts/login/')
            else:
                  print (form.errors)
      else:
            form = SignUpForm()
      SigUpForm = {'form': form}
      return render( request , 'benpelumiscrumy/signUp.html', SigUpForm)
      # goals = 'keep learning django'
      # return HttpResponse(goals) 
   
 
@login_required(login_url='../accounts/login') 
def move_goal(request , goal_id):
      dictionary = {'error': 'A record with that goal id does not exist'}
      validUser = request.user
      try: 
        obj = ScrumyGoals.objects.get(goal_id = goal_id)
      except ObjectDoesNotExist:
         return render(request, 'benpelumiscrumy/exception.html', dictionary) 
      else:   
         if validUser.is_authenticated:
            if validUser.groups.filter(name = 'Developer').exists():
               if request.method == 'POST':
                  form = EditGoalForm(request.POST, instance= obj)
                  if obj.user == validUser:
                     if form.is_valid():
                        if GoalStatus.objects.get(status_name = 'Done Goal') != obj.goal_status:
                           new_goal = form.save(commit = False)
                           new_goal.save()
                           return redirect('/benpelumiscrumy/home/')

                        else:
                           return HttpResponse('your not permitted to move to done goal')   
                        
                  else:
                     return HttpResponse('you can only move your goals')   
      
               else:
                  form = EditGoalForm(instance=obj)
               return render(request, 'benpelumiscrumy/addGoal.html', {'form': form})   
            elif validUser.groups.filter(name = 'Quality Assurance').exists():
               if request.method == 'POST':
                  form = EditGoalForm(request.POST, instance=obj)   
                  if form.is_valid():
                     new_goal = form.save(commit = False)
                     new_goal.save()
                     return redirect('/benpelumiscrumy/home/')
                
               else:
                  form = EditGoalForm(instance=obj)
               return render(request, 'benpelumiscrumy/addGoal.html', {'form': form})

            elif validUser.groups.filter(name = 'Admin').exists(): 
               if request.method == 'POST':
                  form =  EditGoalForm(request.POST, instance=obj)  
                  if form.is_valid():
                     new_goal = form.save(commit = False)
                     new_goal.save()
                     return redirect('/benpelumiscrumy/home/')

               else:
                  form = EditGoalForm(request.POST, instance = obj)
               return render(request, 'benpelumiscrumy/addGoal.html', {'form': form})    

            elif validUser.groups.filter(name = 'Owner').exists(): 
               if request.method == 'POST':
                  form = EditGoalForm(request.POST, instance=obj )
                  if obj.user == validUser:
                     if form.is_valid():
                        new_goal = form.save(commit = False)
                        new_goal.save()
                        return redirect('/benpelumiscrumy/home')     
                  else:
                     return HttpResponse('not this users goal')
               else:
                  form = EditGoalForm(request.POST, instance = obj)
               return render(request, 'benpelumiscrumy/addGoal.html', {'form': form}) 
            else:
               form = EditGoalForm(request.POST, instance = obj)
            return render(request, 'benpelumiscrumy/addGoal.html', {'form': form}) 



@login_required(login_url='../accounts/login')
def add_goal(request):  
      validUser = request.user
      if validUser.is_authenticated:
         if validUser.groups.filter(name= 'Developer').exists() or validUser.groups.filter(name = 'Quality Assurance').exists() or validUser.groups.filter(name= 'Owner').exists():
            temp = CreateGoalForm()
            if request.method == 'POST':   
               temp = CreateGoalForm(request.POST)
               if temp.is_valid():
                  temp = temp.save(commit = False)
                  # temp.goal_status = GoalStatus.objects.create(status_name = 'Done Goal')
                  temp.goal_status = GoalStatus.objects.last()
                  temp.user = validUser
                  temp.goal_id = randint(1000, 9999) 
                  temp.save()
                  return redirect('/benpelumiscrumy/home/')
               else:
                  print (temp.errors)
            else:
               form = CreateGoalForm()
            GoalFormDictionary = {'form': form, 'user': validUser}
            return render( request , 'benpelumiscrumy/addGoal.html', GoalFormDictionary)
         else:
            return HttpResponse('you are not allowed to create a goal')      
      else:
         return HttpResponse('please sign in')

      

     
     
# LAB 16
#  1
    #    With your home view in place, redefine it such that it passes a context containing 
    #    the following dictionary values to the home.html template for rendering: 
    #    I) all existing users on the User model. 
    #    II) every goal that falls under Weekly Goals 
    #    II) All goals under Daily Goals 
    #    IV) All goals under Verify Goals
    #     V) All goals under Done Goals

#  2    
    # While maintaining the current table headings of your html table,
    # construct the table body such that a particular user instance occupies
    # one row of the table with the username occupying the user column 
    # and all its goals should also fall within that row.
    # Ensure that any goal with a status Weekly Goal will fall under the column weekly goal,
    # any goal with status Daily Goal will fall under the column Daily Goals same should apply to verify
    #  and Done goals with each goal having its goal_id and goal_name being displayed.


@login_required(login_url='../accounts/login')
def home (request):
      user = User.objects.all()
      # obj = ScrumyGoals.objects.get(goal_id = goal_id)
      # obj2 = obj.goal_id
      # obj = args = (obj2))

      allWeeklyGoals = GoalStatus.objects.get(status_name = 'Weekly Goal')
      allWeeklyGoals = allWeeklyGoals.scrumy_goal.all()

      allDailyGoals = GoalStatus.objects.get(status_name = 'Daily Goal')
      allDailyGoals = allDailyGoals.scrumy_goal.all()

      allVerifyGoals = GoalStatus.objects.get(status_name = 'Verify Goal')
      allVerifyGoals = allVerifyGoals.scrumy_goal.all()

      allDoneGoals = GoalStatus.objects.get(status_name = 'Done Goal')
      allDoneGoals = allDoneGoals.scrumy_goal.all()

      dictionaryValues = { 'users': user , 'weekly_goals': allWeeklyGoals, 'daily_goals': allDailyGoals,
                         'verify_goals': allVerifyGoals , 'done_goals': allDoneGoals, }
      return render(request, 'benpelumiscrumy/home.html' ,dictionaryValues )


# def get_absolute_url (self):
#       return reverse('movegoal', kwargs = {'id', self.id})

def homealone (request, goal_id):
      obj = ScrumyGoals.objects.get(goal_id = goal_id)
      user = User.objects.get()
      return HttpResponse(obj.goal_id)
# def current_datetime(request):
#     now = datetime.datetime.now()
#     html = "<html><body>It is now %s.</body></html>" % now
#     return HttpResponse(html)


# def learningDjango(request) :
     
# goalId = randint(1000, 9999)
      # goalStatus = GoalStatus.objects.last()
      # addGoalUser = User.objects.get(username = 'louis')
      # addGoal = ScrumyGoals.objects.create(goal_name = 'keep learning django', goal_id = goalId, created_by = 'Louis' , moved_by = 'Louis', owner = 'Louis' , goal_status = goalStatus ,user = addGoalUser ) 
      # return HttpResponse(addGoal)
 


# get_grading_parameters"Welcome to Django"

myscrumy/django-benpelumiscrumy/benpelumiscrumy/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse 


def homePage(request) :
     return HttpResponse("Welcome to Django")

# def index(request):
#     return render(request, 'benpelumiscrumy/index.html', {})

# get_grading_parameters

benpelumiscrumy/templates/benpelumiscrumy/addGoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p> {{request.user.username}} is logged in </p>
    <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <button type="submit">Save</button>
    </form>
    
</body>
</html>

benpelumiscrumy/templates/benpelumiscrumy/addGoalInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="post" action="">
        {% csrf_token %}
        <button type="submit" name="save" value="save">Save</button>
        <input type="text" name="item">
        <button type="submit" name="newItem" value="newItem"> Add Item</button>
    </form>
</body>
</html>

benpelumiscrumy/templates/benpelumiscrumy/exception.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p> {{error}}</p>
</body>
</html>  -->

<!-- <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Error</title>
        <style>
            body {
                color: gainsboro;
                background-color: #ecebeb;
            }
            p{
                text-align: center;
                position: absolute;
                font-family: Georgia, 'Times New Roman', Times, serif;
                font-size: xx-large;
                color: #000;
            }
        </style>
    </head>
    <body>
        <p>{{error}}</p> 
    </body>
</html> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta http-equiv="X-UA-Compatible" content="ie=edge"> -->
    <title> Error </title>
    <style>
        body {
            color: #b8b2b2;
            background-color: #ecebeb;
        }
        p {
            text-align: center;
            font-size:  36px;
            color: #000;
        }
    </style>
</head>
<body>
    <p> {{request.user.username}} is logged in </p>
    <p>{{error}}</p>

    
</body>
</html>

benpelumiscrumy/templates/benpelumiscrumy/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
        </style>
</head>
<body>
  <p> {{request.user.username}} is logged in </p>
    <table>
        <tr>
            <th>User</th>
            <th>Weekly Goals</th>
            <th>Daily Goals</th>
            <th>Verify Goals</th>
            <th>Done Goals</th>
        </tr>
       
        <tbody>
          {%for user in users%}
          <tr>
            <td>
              {{user.username}}
            </td>
            
            <td>
              
              {% for user_goal in user.goal_owner.all %}
              {% if user_goal in weekly_goals %}
              <a href="{% url 'benpelumiscrumy:moveGoal' goal_id=user_goal.goal_id %}">
              {{user_goal.goal_name}}: {{user_goal.goal_id}}
              </a>
              {% endif %}
              {% endfor %}
              
            </td>
            <td>
              {% for user_goal in user.goal_owner.all %}
              {% if user_goal in daily_goals %}
              <a href="{% url 'benpelumiscrumy:moveGoal' goal_id=user_goal.goal_id %}">
              {{user_goal.goal_name}}: {{user_goal.goal_id}}
              </a>
              {% endif %}
              {% endfor %}
            </td>
            <td>
              {% for user_goal in user.goal_owner.all %}
              {% if user_goal in verify_goals %}
              <a href="{% url 'benpelumiscrumy:moveGoal' goal_id=user_goal.goal_id %}">
              {{user_goal.goal_name}}: {{user_goal.goal_id}}
              </a>
              {% endif %}
              {% endfor %}
            </td>
            <td>
              {% for user_goal in user.goal_owner.all %}
              {% if user_goal in done_goals %}
              <a href="{% url 'benpelumiscrumy:moveGoal' goal_id=user_goal.goal_id %}">
              {{user_goal.goal_name}}: {{user_goal.goal_id}}
              </a>
              {% endif %}
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
          </tbody>
    </table>
    <a href="{% url 'benpelumiscrumy:addGoal' %}"> Add a goal here</a>
</body>
</html>

benpelumiscrumy/templates/benpelumiscrumy/moveGoalForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p> {{request.user.username}} is logged in </p>
    <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <button type="submit">Save</button>
    </form>
    
</body>
</html>

benpelumiscrumy/templates/benpelumiscrumy/signUp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <button type="submit">Save</button>
    </form>
    
</body>
</html>